[package]
name = "my-telemetry-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-settings-reader = { tag = "0.1.5", git = "https://github.com/MyJetTools/my-settings-reader.git", features = [
    "background-reader",
] }
flurl = { tag = "0.4.0", git = "https://github.com/MyJetTools/fl-url.git" }

dioxus = "*"
dioxus-desktop = "*"
dioxus-liveview = { varsion = "*", features = ["salvo"] }
dioxus-ssr = "*"
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_yaml = "*"
futures = "*"
tonic = { version = "*", features = ["tls", "tls-roots", "prost"] }
anyhow = "*"
prost = "*"
prost-types = "*"
fermi = "*"
futures-util = "*"
salvo = { version = "*", features = ["full", "affix", "ws"] }
once_cell = "*"
async-trait = "*"
lazy_static = "*"
